a1 = Account.create(first_name: "Sam", last_name: "Ponce", user_name: "Sam_P", password_digest: "SAMANTHA", email: "samp@hotmail.com")
p1 = Post.create(account: a1, image: "test", description: "first post")
l1 = Like.create(account: a1, post: p1)
c1 = Comment.create(account: a1, post: p1)
f1 = Follower.create(account: a1, follower_id:"1")
